dental/dental/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

dental/index/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^doctors/$', views.DoctorListView.as_view(), name='doctors'),
    re_path(r'^doctors/(?P<pk>\d+)$', views.DoctorDetailView.as_view(), name='doctor-detail'),

    re_path(r'^doctors/create/$', views.create_doctor, name='create_doctor'),
    re_path(r'^doctors/(?P<pk>\d+)/renew/$', views.update_doctor, name='update_doctor'),
    re_path(r'^doctors/(?P<pk>\d+)/delete/$', views.delete_doctor, name='delete_doctor'),

    re_path(r'^procedure_types/$', views.ProcedureTypeListView.as_view(), name='procedure_types'),
    re_path(r'^procedure_types/create/$', views.create_procedure_type, name='create_procedure_type'),
    re_path(r'^procedure_types/(?P<pk>\d+)/renew/$', views.update_procedure_type, name='update_procedure_type'),
    re_path(r'^procedure_types/(?P<pk>\d+)/delete/$', views.delete_procedure_type, name='delete_procedure_type'),


    re_path(r'^my_procedures/$', views.LoanedProceduresByUserListView.as_view(), name='my_procedures'),
    re_path(r'^all_procedures/$', views.ProceduresListView.as_view(), name='all_procedures'),

    re_path(r'^all_procedures/create_procedure/$', views.create_procedure_admin, name='create_procedure_admin'),
    re_path(r'^all_procedures/(?P<pk>\d+)/renew/$', views.update_procedure, name='update_procedure'),
    re_path(r'^all_procedures/(?P<pk>\d+)/delete/$', views.delete_procedure, name='delete_procedure'),
    re_path(r'^create_procedure/$', views.create_procedure_user, name='create_procedure'),
]

dental/index/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from PIL import Image


class ProcedureType(models.Model):

    name = models.CharField(
        max_length=100, verbose_name='Назва процедури'
    )

    price = models.IntegerField(
        verbose_name='Ціна процедури'
    )

    details = models.TextField(max_length=200, verbose_name='Деталі')

    class Meta:
        ordering = ['name']
        permissions = (
            ('can_edit_procedure_type', 'Може редагувати послуги'),
            ('can_add_procedure_type', 'Може додавати послуги'),
            ('can_delete_procedure_type', 'Може видаляти послуги')
        )

    def __str__(self):
        return self.name


class Procedure(models.Model):

    date_time = models.DateTimeField(
        verbose_name='Дата та час проведення процедури'
    )

    patient = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='Пацієнт'
    )

    doctor = models.ForeignKey(
        'Doctor', on_delete=models.CASCADE, verbose_name='Лікар'
    )

    procedure_type = models.ManyToManyField(
        'ProcedureType', verbose_name='Назва процедури'
    )

    LOAN_STATUS = (
        ('p', 'Заплановано'),
        ('c', 'Підтверджено'),
        ('d', 'Виконано'),
        ('o', 'Прострочено')
    )

    status = models.CharField(
        max_length=1, choices=LOAN_STATUS, default='p', verbose_name='Статус процедури'
    )

    details = models.TextField(
        max_length=200, blank=True, null=True, verbose_name='Деталі'
    )

    class Meta:
        ordering = ['date_time']
        permissions = (
            ('can_edit_procedure', 'Може редагувати процедури'),
            ('can_add_procedure', 'Може додавати процедури'),
            ('can_delete_procedure', 'Може видаляти процедури')
        )

    def __str__(self):
        return f'Пацієнт: {self.patient}, Доктор: {self.doctor}, Дата та час: {self.date_time}'

    def get_absolute_url(self):
        return reverse('procedure-detail', args=[str(self.id)])


class Doctor(models.Model):

    first_name = models.CharField(
        max_length=50, verbose_name="Ім'я"
    )

    last_name = models.CharField(
        max_length=50, verbose_name='Прізвище'
    )

    middle_name = models.CharField(
        max_length=50, verbose_name='По-Батькові'
    )

    phone = models.CharField(
        max_length=15, verbose_name='Номер телефону'
    )

    email = models.EmailField(
        max_length=30, verbose_name='Електронна адреса'
    )

    LOAN_SPECIALIZATION = (
        ('ther', 'Терапевтична стоматологія'),
        ('orth', 'Ортодонтія'),
        ('oral', 'Хірургічна стоматологія'),
        ('endo', 'Ендодонтія'),
        ('peri', 'Періодонтологія'),
        ('pedi', 'Педіатрична стоматологія'),
        ('pros', 'Протезування')
    )

    specialization = models.CharField(
        max_length=4, choices=LOAN_SPECIALIZATION, verbose_name='Спеціалізація'
    )

    photo = models.ImageField(verbose_name='Фото лікаря')

    class Meta:
        ordering = ['specialization']
        permissions = (
            ('can_edit_doctor', 'Може редагувати лікарів'),
            ('can_delete_doctor', 'Може видаляти лікарів'),
            ('can_add_doctor', 'Може додавати лікарів')
        )

    def __str__(self):
        return f'{self.last_name} {self.first_name} {self.middle_name}'

    def get_absolute_url(self):
        return reverse('doctor-detail', args=[str(self.id)])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.photo.path)
        output_size = (400, 400)
        img.thumbnail(output_size)
        img.save(self.photo.path)

dental/index/templates/all_procedures.html
{% extends 'base.html' %}
{% block title %}Усі процедури{% endblock title %}
{% block content %}
    <h1 class="display-2">Усі процедури</h1>

    {% if procedures %}
        {% for procedure in procedures %}
            <div class="
                {% if procedure.status == 'o' %}alert alert-danger
                {% elif procedure.status == 'c' %}alert alert-primary
                {% elif procedure.status == 'd' %}alert alert-success
                {% else %}alert alert-dark
                {% endif %}">
                <h1><strong>
                    {% for procedure_type in procedure.procedure_type.all %}
                        {{ procedure_type }}
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </strong></h1>
                <p><strong>Дата та час: </strong>{{ procedure.date_time }}</p>
                <p><strong>Пацієнт: </strong>{{ procedure.patient }}</p>
                <p><strong>Доктор: </strong>{{ procedure.doctor }}</p>
                <p><strong>Статус: </strong>{{ procedure.get_status_display }}</p>
                <p><strong>Деталі: </strong>{{ procedure.details }}</p>
                <div class="btn-group">
                    <a class="btn btn-sm btn-outline-primary mx-3" href="{% url 'update_procedure' procedure.id %}">Редагувати процедуру</a>
                    <a class="btn btn-sm btn-outline-danger mx-3" href="{% url 'delete_procedure' procedure.id %}">Видалити процедуру</a>
                </div>
            </div>
            <br>
      {% endfor %}

    {% else %}
      <p>Немає нічого (((</p>
    {% endif %}
{% endblock %}

dental/index/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <title>{% block title %}Default Title{% endblock title %}</title>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    {% load permissions_tags %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/5b6b903be4.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% block sidebar %}
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
            <h1 class="my-0 mr-md-auto font-weight-normal">
                <i class="fa-solid fa-tooth mx-3">Стоматологія DENT</i>
            </h1>
            <nav class="my-2 my-md-0 mr-md-3">
                <a class="p-2 text-dark fs-4 mx-1" href="{% url 'index' %}">
                    <i class="fa-solid fa-house"> Головна</i></a>
                <a class="p-2 text-dark fs-4 mx-1" href="{% url 'doctors' %}">
                    <i class="fa-solid fa-user-doctor"> Лікарі</i></a>
                {% if user|has_perm:"index.can_add_doctor" %}
                    <a class="btn btn-sm btn-outline-primary" href="{% url 'create_doctor' %}">Додати лікаря</a>
                {% endif %}
                <a class="p-2 text-dark fs-4 mx-1" href="{% url 'procedure_types' %}">
                    <i class="fa-solid fa-file"> Список послуг</i></a>
                {% if user|has_perm:"index.can_add_procedure_type" %}
                    <a class="btn btn-sm btn-outline-primary" href="{% url 'create_procedure_type' %}">Додати послугу</a>
                {% endif %}
                {% if user|in_group:"patients" %}
                    <a class="p-2 text-dark fs-4 mx-1" href="{% url 'my_procedures' %}">
                        <i class="fa-solid fa-bed-pulse"> Мої процедури</i></a>
                    <a class="p-2 text-dark fs-4 mx-1" href="{% url 'create_procedure' %}">
                        <i class="fa-solid fa-hospital"> Записатись на процедуру</i></a>
                <strong class="p-2 text-dark fs-4 mx-1"><i class="fa-solid fa-user"></i> {{ user.username }}</strong>
                {% elif user|in_group:"admins" %}
                    <a class="p-2 text-dark fs-4 mx-1" href="{% url 'all_procedures' %}">
                        <i class="fa-solid fa-list"> Всі процедури</i></a>
                    <a class="btn btn-sm btn-outline-primary" href="{% url 'create_procedure_admin' %}">Додати процедуру</a>
                    <strong class="p-2 text-dark fs-4 mx-1"><i class="fa-solid fa-user-tie"></i> ADMIN</strong>
                {% endif %}
            </nav>
            {% if user.is_authenticated %}
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button class="btn btn-outline-danger mx-5 fs-5" type="submit">Вийти</button>
                </form>
            {% else %}
                <a class="btn btn-outline-primary mx-2 fs-5" href="{% url 'login' %}">Увійти</a>
                <a class="btn btn-outline-primary mx-2 fs-5" href="{% url 'register' %}">Зареєструватись</a>
            {% endif %}
        </div>
    {% endblock sidebar %}

    <div class="container">
        {% block content %} {% endblock content %}
    </div>

    {% block pagination %}
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">попередня</a>
                    {% endif %}
                    <span class="page-current">
                        Сторінка {{ page_obj.number }} з {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">наступна</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
    {% endblock %}
</body>
</html>

dental/index/templates/create_update.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
    <h1>{{ title }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

dental/index/templates/delete.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
    <h1>Видалити: {{ model }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Видалити</button>
        <a href="{% url back %}">Відміна</a>
    </form>
{% endblock %}

dental/index/templates/doctors.html
{% extends 'base.html' %}
{% block title %}Лікарі{% endblock title %}
{% block content %}
{% load permissions_tags %}

    <div class="album py-5 bg-light">
        <div class="container">
            <h1 class="display-2">Список лікарів</h1>
            <div class="row">
                {% if doctors %}
                    {% for doctor in doctors %}
                        <div class="col-md-4">
                            <div class="card mb-4 box-shadow">
                                <img class="card-img-top" src="{{ doctor.photo.url }}" data-holder-rendered="true">
                                <div class="card-body">
                                    <p class="card-text">Лікар: <strong>{{ doctor.last_name }} {{ doctor.first_name }}</strong></p>
                                    <p class="card-text">Спеціалізація: <strong>{{ doctor.get_specialization_display }}</strong></p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a class="btn btn-sm btn-outline-secondary" href="{{ doctor.get_absolute_url }}">Детальніше</a>
                                            {% if request.user|has_perm:"index.can_edit_doctor" %}
                                                <a class="btn btn-sm btn-outline-primary" href="{% url 'update_doctor' doctor.id %}">Змінити</a>
                                            {% endif %}
                                            {% if request.user|has_perm:"index.can_delete_doctor" %}
                                                <a class="btn btn-sm btn-outline-danger" href="{% url 'delete_doctor' doctor.id %}">Видалити</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>Жодного доктора</p>
                {% endif %}
            </div>

        </div>
    </div>

{% endblock content %}

dental/index/templates/index.html
{% extends 'base.html' %}
{% block title %}Стоматологія DENT{% endblock title %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-1"> Стоматологія Дент</h1>
      <p class="lead display-5">Кількість лікарів: {{ num_doctors }}.</p>
      <p class="lead display-5">Кількість доступних послуг: {{ num_procedure_type }}.</p>
      <p class="lead display-5">Кількість пацієнтів: {{ num_patient }}.</p>
    </div>
{% endblock content %}

dental/index/templates/my_procedures.html
{% extends 'base.html' %}
{% block title %}Мої процедури{% endblock title %}
{% block content %}
    <h1 class="display-2">Мої процедури</h1>

    {% if procedure_list %}

        {% for procedure in procedure_list %}
            <div class="
            {% if procedure.status == 'o' %}alert alert-danger
            {% elif procedure.status == 'c' %}alert alert-primary
            {% elif procedure.status == 'd' %}alert alert-success
            {% else %}alert alert-dark
            {% endif %}">
                <h1><strong>
                    {% for procedure_type in procedure.procedure_type.all %}
                        {{ procedure_type }}
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </strong></h1>
                <p><strong>Дата та час: </strong>{{ procedure.date_time }}</p>
                <p><strong>Доктор: </strong>{{ procedure.doctor }}</p>
                <p><strong>Статус: </strong>{{ procedure.get_status_display }}</p>
                <p><strong>Деталі: </strong>{{ procedure.details }}</p>
            </div>
        {% endfor %}

    {% else %}
        <p>У вас немає жодної процедури.</p>
    {% endif %}
{% endblock %}

dental/index/templates/procedure_types.html
{% extends 'base.html' %}
{% block title %}Процедури{% endblock title %}
{% block content %}
{% load permissions_tags %}
    <h1 class="display-2">Список процедур</h1>
    {% if procedure_types %}
        {% for procedure_type in procedure_types %}
            <div class="alert alert-info">
                <h1>Процедура: <strong>{{ procedure_type.name }}</strong></h1>
                <p>Мінімальні ціна: <strong>{{ procedure_type.price }}</strong></p>
                <p>Деталі: <strong>{{ procedure_type.details }}</strong></p>
                {% if user|in_group:"admins" %}
                    <div class="btn-group">
                        <a class="btn btn-sm btn-outline-primary mx-3" href="{% url 'update_procedure_type' procedure_type.id %}">Редагувати послугу</a>
                        <a class="btn btn-sm btn-outline-danger mx-3" href="{% url 'delete_procedure_type' procedure_type.id %}">Видалити послугу</a>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    {% else %}
        <p>Немає нічого((</p>
    {% endif %}
{% endblock content %}